services:
     api:
          environment:
               NODE_ENV: development
          volumes:
               - ./src:/app/src
               - ./prisma:/app/prisma
          command: >
               sh -c "
               pnpm prisma generate &&
               pnpm tsx watch src/index.ts
               "
