services:
     api:
          environment:
               NODE_ENV: development
          volumes:
               - ./src:/app/src # hot-reload
               - ./prisma:/app/prisma
          command: >
               sh -c "
               pnpm prisma generate &&
               pnpm ts-node-dev --respawn --transpile-only src/index.ts
               "
