services:
     db:
          image: postgres:15
          container_name: fin_wss_db
          restart: always
          environment:
               POSTGRES_USER: ${POSTGRES_USER}
               POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
               POSTGRES_DB: ${POSTGRES_DB}
          ports:
               - "${POSTGRES_PORT:-5433}:5432"
          volumes:
               - postgres_data:/var/lib/postgresql/data
volumes:
     postgres_data:
